[2025-06-14 22:49:04,613] 10 root - INFO - >>>>>> stage Data Ingestion stage started <<<<<<
[2025-06-14 22:49:04,615] 32 root - INFO - yaml file: config\config.yaml loaded successfully
[2025-06-14 22:49:04,615] 52 root - INFO - created directory at: artifacts
[2025-06-14 22:49:04,616] 52 root - INFO - created directory at: artifacts/data_ingestion
[2025-06-14 22:49:04,616] 24 root - INFO - Downloading data from https://drive.google.com/file/d/1nmR9kchQlUZk0PQMx_NnRMCBgggfWBeZ/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2025-06-14 22:53:41,413] 30 root - INFO - Downloaded data from https://drive.google.com/file/d/1nmR9kchQlUZk0PQMx_NnRMCBgggfWBeZ/view?usp=sharing into file artifacts/data_ingestion/data.zip
[2025-06-14 22:53:50,031] 47 root - INFO - Extracted zip file into artifacts/data_ingestion
[2025-06-14 22:53:50,033] 13 root - INFO - >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-06-14 22:53:50,033] 21 root - INFO - *******************
[2025-06-14 22:53:50,034] 22 root - INFO - >>>>>> stage Prepare base model started <<<<<<
[2025-06-14 22:53:50,035] 32 root - INFO - yaml file: config\config.yaml loaded successfully
[2025-06-14 22:53:50,036] 52 root - INFO - created directory at: artifacts
[2025-06-14 22:53:50,036] 52 root - INFO - created directory at: artifacts/prepare_base_model
[2025-06-14 22:53:50,036] 27 root - ERROR - 'ConfigurationManager' object has no attribute 'params'
Traceback (most recent call last):
  File "E:\DL projects\Pneumonia-classification-projects\main.py", line 24, in <module>
    prepare_base_model.main()
  File "E:\DL projects\Pneumonia-classification-projects\src\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "E:\DL projects\Pneumonia-classification-projects\src\config\configuration.py", line 42, in get_prepare_base_model_config
    params_image_size=self.params.IMAGE_SIZE,
AttributeError: 'ConfigurationManager' object has no attribute 'params'
